// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sphtxwwdmvprdihasagr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwaHR4d3dkbXZwcmRpaGFzYWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzU3ODEsImV4cCI6MjA2MTYxMTc4MX0.6JBBl7MTC4OtGjYhtmLJubMqD0pOmXX4k7PJgUlMpAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);